<a href="https://colab.research.google.com/github/Rjricafrente227/NUMERICAL-METHOD/blob/main/Matrix_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and it's operation



In [ ]:
import numpy as np
a = np.array([1,2,3])
a[0]=4
print (a)


[4 2 3]


In [ ]:
import numpy as np
b = np.array([[1,2,3], [4,5,6]]) 
b[0,0]=7
print(b)



[[7 2 3]
 [4 5 6]]


In [ ]:
import numpy as np 
c =np.array([[1,2,3,],[4,5,6],[6,7,8]])
print(c)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
import numpy as np
d= np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [ ]:
import numpy as np
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
e=np.diagonal([[1,2,3,],[4,5,6],[7,8,9]])

print(e)

[1 5 9]


In [ ]:
import numpy as np
f = np.empty((0,10))
print(f)

[]


In [ ]:
import numpy as np
g= np.zeros((2,2)) 
print(g)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
e = np.eye(2)
g= np.zeros((2,2)) 
print(e)
print(g)
print(e+g)
print(e-g)
print(g-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
