<a href="https://colab.research.google.com/github/Rjricafrente227/NUMERICAL-METHOD/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Prelim exam


In [ ]:
import numpy as np
(a) = np.array ([[1, 2, 3],[2, 3, 3],[3, 4, -2]])
print(A)

B = np.array ([36])
C = np.array ([-31])
e= (B+C)
print(e)
print (round(np.linalg.det(a)))
print (np.linalg.det(a))


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[5]
5
5.000000000000001
