<a href="https://colab.research.google.com/github/Rjricafrente227/NUMERICAL-METHOD/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Matrix and It's Operations


In [ ]:
import numpy as np

A = np.array ([[-5, 0],[4, 1]])
B = np.array ([[6, 3],[2, 3]])
print(A)
print(B)
#Addition
c = A + B
print(c) 

#Substraction
d = B-A
print(d)

#Substruction
e = A-B
print(e)


[[-5  0]
 [ 4  1]]
[[6 3]
 [2 3]]
[[1 3]
 [6 4]]
[[11  3]
 [-2  2]]
[[-11  -3]
 [  2  -2]]
